name:                312Minesweeper
version:             0.1.0.0
github:              "MrEvildoom/312Minesweeper"
license:             BSD3
author:              "Jack Heidal"
maintainer:          "JPHeidal@gmail.com"
copyright:           "2021 Jack Heidal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MrEvildoom/312Minesweeper#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  312Minesweeper-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 312Minesweeper

tests:
  312Minesweeper-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 312Minesweeper
